name: flutter_wechat_tailwind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_tailwind:
    path: ../../flutter_tailwind
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  dio: ^5.4.1
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  permission_handler: ^11.3.1
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  intl: ^0.19.0
#  flutter_local_notifications: ^16.3.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

#  assets:
#    - assets/images/
#    - assets/icons/
#    - assets/fonts/
#    - .env
#    - .env.dev
#    - .env.prod

#  fonts:
#    - family: WeChat
#      fonts:
#        - asset: assets/fonts/WeChat-Regular.ttf
